### ISSUE TITLE
Some gifs do not convert

### ISSUE THREAD

**Issue by nikgtasa** [JacobDev1/xl-converter#10]
Hello. Win10, 22h2, cpu 5700x. Converted a large batch of gifs and some of them gave me errors without really explaining what that error is. I tried converting them to webp as well and they all came out empty, zero bytes.
[xl_converter_exceptions.csv](https://github.com/JacobDev1/xl-converter/files/14264597/xl_converter_exceptions.csv)

**Comment by JacobDev1** [comment]
Hello,

It's good you have included the debug file.

The issue is related to the "Lossless (only If smaller)" options, try disabling it. When converting from GIF, the smallest file is always lossy.
 
For animated images, I advise using either FFmpeg or cjxl (from libjxl) instead.

I will investigate this bug further.

**Comment by nikgtasa** [comment]
I tried again, this time putting all of the gifs in and making sure the duplicates are skipped. This time i wasn't graced with an error log, just a completion. I tried converting only one gif that i knew wasn't getting converted before and it still refuses to. The error does occur if i select lossless (only if smaller) but otherwise it just doesn't convert at all. I also tried changing effort but to no avail. Likewise, webp failed as well.

**Comment by JacobDev1** [comment]
For JPEG XL, you should try to convert your GIF using `cjxl` command line utility. You will find it in the installation directory - `xl-converter/bin/win`. You can add this folder to the Windows' PATH.

```cmd
cjxl animated.gif animated.jxl 
```

If this doesn't work, your GIFs may be corrupted.

When it comes to WEBP, the included version of ImageMagick requires all frames to have the same resolution. Normally passing `-coalesce` solves this issue, but this time it does not seem to work. New versions of ImageMagick do work though. I'll look into it.

Animated images are outside of the score of this project. Support for them in XL Converter is considered deprecated.

**Comment by nikgtasa** [comment]
I would just prefer to use your program, it's way easier to handle and i love that. As for being corrupted, i'm not sure about it. They still play fine and i've used czkawka to search for any broken files before i started converting and nothing came up. I did get this error with cjxl though. I went to ezgif and converted gif to gif and then converted the result to jxl with your program and it worked fine. Thanks for trying to help anyway.
![image](https://github.com/JacobDev1/xl-converter/assets/38408810/0b68c230-96d0-40d1-8b69-78aa157975aa)

**Comment by JacobDev1** [comment]
Images can be both corrupted and viewable at the same time. However, converting them will result in an error.

Here is how you check for errors with FFmpeg.
```
ffmpeg -v error -i animation.gif -f null -
```
Note, that there is no reliable way of verifying GIFs for corruption.

I'm happy to see you like using my software. Unfortunately, animated images are one thing I'd rather avoid. I do not want to take on more work than I can handle.
