### ISSUE TITLE
JPEG XL version 0.10.0

### ISSUE THREAD

**Issue by Ahmad-Amsyar** [JacobDev1/xl-converter#12]
Will XL Converter update the JPEG XL from version 0.8.1 to version 0.10.0?

I created a pull request for Windows (e0bbe3f) before I realize you said you will ignore PL in the README.

**Comment by JacobDev1** [comment]
XL Converter will feature newer binaries. However, I need to conduct extensive testing before the upgrade.

I have included a thorough explanation [here](https://github.com/JacobDev1/xl-converter/pull/11#issuecomment-1966611453).

**Comment by JacobDev1** [comment]
The next version (`0.9.8`) will feature newer `libjxl` binaries.

The development build already features `0.10.1`, with `0.10.2` currently being validated.

**Comment by Ahmad-Amsyar** [comment]
Thank you for the update. I really appreciate your hardwork. Hope your tool will grow bigger.

**Comment by JacobDev1** [comment]
Version `0.9.8` was just released. `libjxl` was updated to `0.10.2`.

[changelog](https://github.com/JacobDev1/xl-converter/releases/tag/v0.9.8)
