### ISSUE TITLE
note: Your software is added to AM package manager repo

### ISSUE THREAD

**Issue by fiftydinar** [JacobDev1/xl-converter#13]
AM is a bash package manager of portable apps for Linux, which contains a repo of AppImage & .tar.gz scripts to download, update, remove & integrate supported apps into desktop environment. With a note that AppImage is main format for AM.

PRs which added your software:
https://github.com/ivan-hc/AM/commit/2ed8c089dc179a94c6b02e1bab0d0dcbd2088dda
https://github.com/Portable-Linux-Apps/Portable-Linux-Apps.github.io/commit/3688b8c690770e02446985df802726108b7dd66d

Info about the project:
https://github.com/ivan-hc/AM

I used your software because it's the only one I know which supports JPEG-XL format for converting images in form of GUI.

libjxl packaged for Fedora doesn't support manipulation of images for some reason,
distroboxes are clunky to setup &
flatpaks which support JPEG-XL converting are not available.

Thanks for your work!

**Comment by JacobDev1** [comment]
Hello,

feel free to include my application.

Here is my email If you ever need to reach out to me directly: contact@codepoems.eu
