### ISSUE TITLE
Flatpak

### ISSUE THREAD

**Issue by mikae1** [JacobDev1/xl-converter#14]
Lovely app this! Is there any chance it could show up in Flathub?

**Comment by JacobDev1** [comment]
Hello,

I'm happy you like it. I have put a lot of time and effort into it.

I'm not currently planning to ship it to Flathub.

I have been playing around with making Flatpak builds. However, the process is non-trivial and I often hit roadblocks. I will be figuring this out more in the future, but I make no promises at the moment.

If you're looking for start menu and desktop icons, feel free to use my custom Linux installer. It is shipped as a `.7z` archive.

**Comment by JacobDev1** [comment]
It just got published on [Flathub](https://flathub.org/apps/eu.codepoems.xl-converter).
