### ISSUE TITLE
Show versions of encoders in release notes

### ISSUE THREAD

**Issue by mikae1** [JacobDev1/xl-converter#15]
There was a lot of improvements for lossless JPEG XL encoding in version 0.10 of libjxl. Looking at the release notes for 0.9.7 of XL Converter I can’t tell if it uses libjxl 0.10 or later. It would be good if release notes for XL Converter showed encoder versions.

**Comment by JacobDev1** [comment]
Hello,

Yes, the changelog will include a notice when the binaries get updated.

The current version uses `0.8.1`. The development build features `0.10.1` with `0.10.2` being currently validated.

I would like to wait for the `libjxl` users to report new bugs as well as do my own testing before the update.

As for lossless improvements. `0.10.2` compared to `0.8.1` with the default Effort of 7 has a worse efficiency on screenshots and a tiny bit better on complex images. It is about the same.

The main difference is speed and RAM usage.
