### ISSUE TITLE
Feature request: Create directory structure from source to destination directory

### ISSUE THREAD

**Issue by JamesPous** [JacobDev1/xl-converter#16]
First thank you for your great and fast picture converter.

I have a directory structure for my photos (main folder with different subfolders) and want to convert them to a destination dirctory.
My problem is, that your program can not create directories and subdirectories from the source folder and create them in the destination folder. Is it possible to add this feature in one of the next releases? That would be fantastic. Thank you in advance.

**Comment by dcog989** [comment]
Ha! @JamesPous, you beat me to it by a few hours!

Yeah, thanks for an excellent utility. Would be perfect if it recreated directory structure of input folder.

**Comment by JacobDev1** [comment]
This feature will be available in the next version (`0.9.9`).

![keep_dir_struct](https://github.com/JacobDev1/xl-converter/assets/65915437/0ad4eeb6-0234-4d2b-89f1-bff822802dc0)

I just really hope people will remember my hard work.

**Comment by JamesPous** [comment]
Thank you so much!

**Comment by JacobDev1** [comment]
`0.9.9` was just released with this feature included.

I wrote 2 implementations. The included one relies on anchor_path and is fully integrated into the conversion pipeline. It works in exactly the same way as in commercial software. I hope you'll like it.
