### ISSUE TITLE
"Disable Delete Original on Startup" not working.

### ISSUE THREAD

**Issue by Ahmad-Amsyar** [JacobDev1/xl-converter#17]
Repoduce:
1) Install version 0.9.8.
2) Open "Settings" tab.
3) Enable "Disable Delete Original on Startup" option.
4) Open "Output" tab.
5) Enable "Delete Original" option.
6) Close the software.
7) Open the software.
8) Open "Output" tab.
9) "Delete Original" option still enabled.

Expectation:
- The option is disabled every startup.

**Comment by JacobDev1** [comment]
Hi,

thank you for reporting this bug. I have just fixed it.

3de7ec6

**Comment by Ahmad-Amsyar** [comment]
Thank you Mr Developer 😄
