### ISSUE TITLE
Small bug with the interface

### ISSUE THREAD

**Issue by Ukhryuk-Hai** [JacobDev1/xl-converter#22]
After start the conversion, a progress window will appear. If minimize the program window and then restore it, the progress window will be compressed vertically. If minimize and restore again, only the title of this window will remain visible.

Let me clarify that I have a 1920*1080 display and 25% image scaling is activated in the Windows settings. I don't know if this has anything to do with the bug.

**Comment by JacobDev1** [comment]
Thanks for pointing this out.

I just fixed it.

The issue was exclusive to Windows and appeared during periods when the dialog wasn't being updated with new data. I added a minimum height to it.
