### ISSUE TITLE
Desktop: no object or moniker (0.9.9)

### ISSUE THREAD

**Issue by snakehill** [JacobDev1/xl-converter#24]
When selecting the uppermost folder in Windows (either as input or output), it gives this error:

![Desktop](https://github.com/JacobDev1/xl-converter/assets/20109369/d901ff7a-3c84-4806-9c62-f973bb8a03ce)

**Comment by JacobDev1** [comment]
Hi,

I can't seem to find a way to reproduce this environment. How did you manage to make the "Desktop" the root item? Please also check how other programs behave when you select that root item.

As far as I've verified, this is the intended Qt behavior. This item doesn't seem to be pointing at a specific directory.

I installed Windows 11 to check this and could not find a way to insert "Desktop" as the root node. It could be a Windows bug.

The other (nested) "Desktop" should work fine as a save location.

**Comment by snakehill** [comment]
In other applications it's recognized just fine, either as "Desktop" or "C:\Users\User\Desktop" but both ending up in the exact same place. The nested one indeed works just as intended.

For me it's the default on Windows 11 machines. Make sure "Show all folders" is checked if you right-click the sidebar.

**Comment by JacobDev1** [comment]
Thanks for checking that on a clean VM. I was able to reproduce this issue.

I checked and VSCode appears to have the exact same issue.

![vscode_no_object_or_moniker](https://github.com/JacobDev1/xl-converter/assets/65915437/518e9b71-a872-4843-84d3-f18aab5156b3)

This looks like either a Windows or a framework issue. There are no exceptions generated.

I don't usually bother with external issues unless they affect most users. 

If you really want this working, you could file an issue to the PySide6 [bug tracker](https://bugreports.qt.io/projects/PYSIDE/issues/).

Requirements: `pyside6==6.6.0`

Minimal reproducible example:

```python
dlg = QFileDialog()
dlg.setWindowTitle("Add Images from a Folder")
dlg.setFileMode(QFileDialog.Directory)

if dlg.exec():
    selected_dir = dlg.selectedFiles()[0]
```

Steps to reproduce: as mentioned before
