### ISSUE TITLE
Using ExifTool - Safe Wipe produces faded image output.

### ISSUE THREAD

**Issue by Lark8037** [JacobDev1/xl-converter#25]
Using ExifTool - Safe Wipe produces faded image output.

**Comment by JacobDev1** [comment]
Use `Encoder` metadata modes to ensure the color profile gets handled properly. In this case, use `Encoder - Wipe`.

By using ExifTool, you handle metadata more thoroughly, but you also run the risk of unexpected behavior.

The ExifTool command used by `ExifTool - Safe Wipe` mode is

 ```bash
exiftool -all= -tagsFromFile @ --icc_profile:all --ColorSpace:all -overwrite_original <dst>
 ```

For more details, refer to [this page in the docs](https://xl-docs.codepoems.eu/metadata)

If you think a newer version of ExifTool will handle your images better, feel free to replace it in `xl-converter/_internal/bin/win`.

**Comment by Lark8037** [comment]
I think you should change this description of docs.
Safe Wipe - deletes all metadata except the one affecting the final image.

**Comment by JacobDev1** [comment]
The commands used by `ExifTool - Preserve` and `ExifTool - Safe Wipe` are set to preserve all color-related information. Unfortunately, this doesn't work 100% of the time.

I'll try to reword some sections of the docs to reflect this better.
