### ISSUE TITLE
Strange behavior of the converter when the disk space runs out

### ISSUE THREAD

**Issue by Ukhryuk-Hai** [JacobDev1/xl-converter#28]
I converted a lot of files (JPG to JXL), and at a certain point I noticed that the result files became very small. More precisely, the first result in the list was small, and the remaining files were zero size. Unfortunately, I did not track the situation properly at that time and, perhaps, some of the files were completely deleted.

I suggest you add a check for free space to the converter (so that user can specify it in the settings), which should take place not only when the conversion starts, but also periodically during the process. If you have any better ideas on how to avoid this problem, please share.

It is also advisable to add a check for the difference in size between the incoming and outgoing files. If the difference is too large (user can adjust the percentage), then this should be displayed in the log and the incoming file should not be deleted.

**Comment by JacobDev1** [comment]
The next version will check if the output file is 0 bytes before finishing the conversion.

Disk space checks may be added in the future.

**Comment by JacobDev1** [comment]
The next update will introduce a check for space left on the device before each file is processed.
