### ISSUE TITLE
The error log window definitely needs improvement

### ISSUE THREAD

**Issue by Ukhryuk-Hai** [JacobDev1/xl-converter#29]
1. I'm using a light theme, but this window still remains dark. In addition, gray font on a black background is difficult to see. On the contrary, such things need to be made clearly visible.

2. Sometimes I needed to see the file name in this window, but by default the width of the name column is too narrow, and when I tried to change the column size, it turned out that this was not possible.

3. If I started the conversion, then minimized the window, the process ended with errors and I try to switch to the program using Alt-Tab, then I switch only to the log window. If I close this window, the main program window will still be minimized.

**Comment by JacobDev1** [comment]
1. Yes, I'll fix it.
2. This could also use some improvements.
3. I'm not yet sure what's the consensus on this behavior in most software.

**Comment by JacobDev1** [comment]
1. The fix will appear in the next update.
2. I'll leave it as it is for now. No matter how many hours I spend on this widget, I can't get it to behave correctly. I may replace it with a list at some point.
3. I'm unsure if this behavior should be changed.
