### ISSUE TITLE
Improved display of the current conversion process and result

### ISSUE THREAD

**Issue by Ukhryuk-Hai** [JacobDev1/xl-converter#32]
I propose to add a docked window at the bottom of the program window, where the current process would be displayed: what files are currently being processed, their size, format and location; if an error occurs, there should be a message in red (an audio signal is also possible). At the end, the total size of the incoming files, the files after conversion and the difference should be indicated.

I'm not saying this is absolutely necessary, but if you someday want to improve your program and sharpen your programming skills at the same time, here's an area where you can put your efforts.

**Comment by JacobDev1** [comment]
These are not bad ideas, but I'm already 2,000 hours into this project. At some point, I need to compromise on the number of features.

PyQt skills are useless in the job market. It's nothing worth sharpening.
