### ISSUE TITLE
Lossless jpeg<->jxl conversion "misleading" UI

### ISSUE THREAD

**Issue by pmiossec** [JacobDev1/xl-converter#34]
First, I'm a new user so sorry if I don't get all the understanding of xl-converter settings.
But from my knowledge of jxl, I had difficult time to try to understand what the conversion will do. So maybe I won't be the only one...

If the user want to convert from jpeg to jxl, the UI is not really clear if it will do a lossless conversion from jpeg to jxl or if it will convert the jpeg to the lossless jxl format. After finding and testing the "Reconstruct JPG from JPEG XL" setting, I now know that it is doing the 1st one. But both could make sense in different use cases. 

I have the feeling that the "Lossless" option has a different behavior depending on the input format and it's difficult for the user to understand it:
* for input in jpg, lossless conversion to jxl (so file is in fact in lossy format)
* for other input formats, output file is in jxl lossless format.

I think some feedback/explanation to the user would be good.
Or some UI changes in the settings. 2 possibilities:
 * a "Lossless conversion from JPG" option
 * 2 different "JPEG XL lossy" and "JPEG XL lossless" output formats.

Another thing:
Is there a good reason to have put the jxl->jpeg lossless conversion "Reconstruct JPG from JPEG XL" in the PNG output format? Or is it a bug?

![image](https://github.com/JacobDev1/xl-converter/assets/460196/709ddfef-3e19-48f9-a497-f323fd6c78fb)

Because I would never look at it here if I wanted to use that feature. It makes more sense to have it in "JPG" format options for me.

Thanks in advance for the feedback.

Note: XL Converter v1.0.0 (Windows)

**Comment by JacobDev1** [comment]
Yes, I was just working on it. Lossless JPEG Recompression will have its own dedicated options in the format selector.

How it currently works is detailed [in the docs](https://xl-docs.codepoems.eu/jpg-reconstruction).

That option under PNG is there, because it was easy to implement this way. Not every JXL file will have reconstruction data, and having PNG as fallback is convenient.

**Comment by JacobDev1** [comment]
I didn't put that option under JPEG for a good reason.

While it seems logical to put this under JPEG, this would result in users accidentally worsening the quality of their images in case reconstruction data isn't found. PNG is lossless and JPEG is lossy.

Dedicated options should clear up any confusion.

**Comment by pmiossec** [comment]
Thanks for the feedback. And for the great work!
