### ISSUE TITLE
french paper about XL-Converter

### ISSUE THREAD

**Issue by zeroheure** [JacobDev1/xl-converter#35]
Hi Jacob 
I've writted a short paper about XL-Converter 1.0. It's in french, with some argotic words. Read it on https://linuxfr.org/news/xl-converter-1-0-billet-d-humeur-et-plaidoyer

**Comment by JacobDev1** [comment]
Hello,

thanks for covering XL Converter. I have read through a translated version of your article.

Feel free to reach out to me directly in the future at: contact@codepoems.eu
