### ISSUE TITLE
Linux installer does not work

### ISSUE THREAD

**Issue by frague59** [JacobDev1/xl-converter#36]
Hi,

The linux installer does not work, due to a mistake in the `install.sh` script

```sh
install.sh: line 64 : [: == : unary operator expected
```

To fix it, just on line 64:
```sh
     if [ $choice == "1" ]; then
```
by
```sh
     if [ $choice = "1" ]; then
``` 

Save, installs runs now...

**Comment by JacobDev1** [comment]
Hi,

thanks for pointing this out. The fix will appear in the next update.

The installer worked on all distros I've tested, so I haven't noticed it up until now.

If anyone is facing this issue, wrap `$choice` in double quotes.

```bash
if [ "$choice" == "1" ]; then
```
