### ISSUE TITLE
A few notes about VC Redist

### ISSUE THREAD

**Issue by Ukhryuk-Hai** [JacobDev1/xl-converter#39]
I have come across a situation many times where after installing some random program, many other programs suddenly stopped working. And each time the reason was that that program silently installed outdated versions of VC Redist. I was forced to uninstall all versions of VC Redist and use a special installer ([this](https://www.techpowerup.com/download/visual-c-redistributable-runtime-package-all-in-one/) or [this](https://github.com/abbodi1406/vcredist)), which would sequentially install the required versions. I also had to use a third-party program (Process Lasso) to prevent these things from being installed secretly.

Therefore, I suggest that you do not repeat the mistakes of others (after all, the version that your converter installs will also one day become outdated) and at least during installation offer a choice whether to install VC Redist or not.

**Comment by JacobDev1** [comment]
Hi,

in `1.0.0` I've added an option to skip the installation of `vc_redist`. Just run the installer from the command line with `/skip_deps`:

```cmd
xl-converter-win-1.0.0-x86_64.exe /skip_deps
```

As far as I've tested, `vc_redist` 2015 - 2022 will just not install if it detects a newer version.

However, I see your point. I'll look into this.

**Comment by JacobDev1** [comment]
In the next version, you'll be able to skip the installation of `vc_redist` in the installer's GUI. `/skip_deps` will be removed as it's no longer needed.
