### ISSUE TITLE
Exif Data

### ISSUE THREAD

**Issue by Ninjasr** [JacobDev1/xl-converter#40]
Exif metadata fails to be carried over to the converted file no matter what settings I use. I've used both the encoder and Exiftool for metadata preservation. This is a deal breaker for me, since I have a lot of photographs that I'd like to convert.

**Comment by JacobDev1** [comment]
What formats did you use? For example, from PNG to JPEG XL.

I assume you are on Windows?

Please, send me one of the source files you find problematic, so I can investigate. Upload it to a service like [Disroot Lufi](https://upload.disroot.org/) and send me a download link to contact@codepoems.eu

**Comment by Ninjasr** [comment]
I converted from JPG to JPEG XL.
I'll send the email right now.
And yes, I am on Windows.

**Comment by JacobDev1** [comment]
Everything works as expected on my end in `1.0.0`.

If you're using ExifTool to view metadata, update it. If not, try a different tool like GIMP.

Assuming the following:
- Downscaling: disabled
- Metadata: `Encoder - Preserve`
- Source format: JPEG

Your file is only run through `cjxl` (the reference JPEG XL encoder). If that's the case, it has to work.

**Comment by JacobDev1** [comment]
Try using other converters such as XnConvert to see if there is any difference.

Keep in mind that metadata in JPEG XL is compressed with Brotli. It's a novel solution that many programs may not support yet.

**Comment by Ninjasr** [comment]
I've done a few more checks and you're correct, it seems that the Exif data is copied over properly. 
Unfortunately, none of the programs I use bar Exiftool seem to display it properly.
I've also tried XnConvert (although very briefly) and it didn't copy over the metadata.
