### ISSUE TITLE
The installer no longer asks where to install the program. This is bad practice.

### ISSUE THREAD

**Issue by Ukhryuk-Hai** [JacobDev1/xl-converter#41]
Why? I usually install in `Program Files / Program Files (x86)` only those programs that are integrated into the system (for example, Windows resets file associations if the program is installed in another location). And all the rest are in another folder `C:\MyPrograms` - this allows them to maintain a certain amount of portability when the settings are written to the program folder, which is quite convenient if I have to reinstall Windows.

**Comment by JacobDev1** [comment]
The installer is using the directory where you had this program installed previously. The directory picker will show up if you don't have it installed.

This is the [standard InnoSetup behavior](https://jrsoftware.org/ishelp/index.php?topic=setup_disabledirpage).

To change the installation directory, simply uninstall the program and install it again. The directory picker should appear. After that, every subsequent installation will use the new directory.

**Comment by Ukhryuk-Hai** [comment]
This is still stupid, the installer should **suggest** the same location, and not **make the decision for the user**. For example, the GOG installer is also based on InnoSetup, but it offers the last folder that was used to install games: that is, not `C:\Games\Ghostrunner`, but `C:\Games` and then the name of the new game. This is really correct and convenient.

**Comment by JacobDev1** [comment]
With InnoSetup installers, you can use the `/DIR` argument to specify a path.

For example:

```cmd
xl-converter-win-1.0.1-x86_64.exe /DIR="C:\Program Files\XL Converter 1.0.1"
```

Alternatively, you can extract every XL Converter installer with `innoextract`.

I'll work on improving the installer.

**Comment by JacobDev1** [comment]
In the next version, the installer will always allow you to choose a directory (even if another version is already installed).
