### ISSUE TITLE
Sometimes, for some unknown reason, after JXL->JPG reconstruction, PNG files appear along with JPG

### ISSUE THREAD

**Issue by Ukhryuk-Hai** [JacobDev1/xl-converter#42]
Let me clarify that the files have the same name, but different extensions. I have not yet discovered any patterns, I can only say that both types of files open normally in the viewer and look the same. As I understand it, if enable the "PNG Fallback" option, then a PNG should be created when it is impossible to "unpack" the JPG from JXL. However, all the files in the folder were created at once with the same encoding parameters and the JPG was successfully unpacked. What's going on?

I cannot provide these files.

**Comment by JacobDev1** [comment]
Does the PNG file have random characters at the end (.e.g "image_a5e.png").

I could not reproduce this issue with the current description. I see you're posting a lot of issues lately. Please use [this template](https://github.com/libjxl/libjxl/blob/main/.github/ISSUE_TEMPLATE/bug_report.md), so I can better understand them. For Environment, just OS and Version are enough. "Steps to reproduce" are important.

You can use `jxlinfo` to check whether a `jxl` image has reconstruction data embedded.

**Comment by Ukhryuk-Hai** [comment]
Yes, it was with random symbols. I also remembered that there were 1 or 2 similar files in the folder, and they were the last in the conversion list.

Okay, next time I will describe in more detail. I just converted everything on the disk, and these images were garbage that I deleted and only the next day I thought that I should have saved them to illustrate the problem.

**Comment by JacobDev1** [comment]
Those are temporary files. If reconstruction data gets detected, no PNG file is ever created. They are probably leftover from some other conversion. However, I can't say for sure without more details.

I'm currently working on bug report templates to make bug reporting smoother.

**Comment by Ukhryuk-Hai** [comment]
So, here's how it went:

I unpacked an old RAR archive with a lot of random pictures in JPG format. And immediately began the conversion process in your program. That is, those PNGs could not possibly be the remnants of the previous conversion. When finished, two PNG files appeared in the folder. As I said, they were last on the conversion list.

The same thing happened again with another archive. There were also two files there and they were the last ones.

In any case, this problem is not serious and you can take your time looking for the exact cause until I or someone else encounters it again and saves the “problem” files.

**Comment by Ukhryuk-Hai** [comment]
Oh, it looks like I haven’t woken up yet and both of these cases are mixed up in my head. Sorry. In one of them, I was doing a JXL-JPG conversion and ran into a problem. And in the other - as described above, with RAR - JPG - JXL conversion. Next time I'll be more careful.

**Comment by JacobDev1** [comment]
If a random PNG appeared, that would indeed be strange. Unfortunately, I was not able to replicate this behavior.

If you find a way to reliably reproduce it, feel free to write "Steps to reproduce".

**Comment by JacobDev1** [comment]
I'll close this issue as it became stale.

Should you encounter this problem again, file a new issue using the "Bug Report" option. I added a set of templates to make this process smoother.
