### ISSUE TITLE
How to enable 10 bits AVIF?

### ISSUE THREAD

**Issue by NeinOclock** [JacobDev1/xl-converter#44]
### Question

I try using -d 10 in the encoder parameters but the conversion fail with the error "output not found" 
[xl_converter_exceptions.csv](https://github.com/user-attachments/files/15980217/xl_converter_exceptions.csv)

### The Docs

- [x] I have read the docs before asking this question.

**Comment by JacobDev1** [comment]
Encoders will match the input's bit depth whenever possible automatically.

As for the `-d 10` in custom params not working. This is a bug in the encoder. If you need this to work, swap `avifenc.exe` in `XL Converter/_internal/bin/win` with the official pre-built. You would be downgrading AOM-AV1 this way, though. Alternatively, you can compile `libavif` yourself.

Binaries are more error-prone when run from `subprocess.run` and Worker, unfortunately.

The Linux version is unaffected by this problem.

**Comment by NeinOclock** [comment]
Thanks! Yes, there is not error in the conversion while using -d 10 on fedora kde

**Comment by JacobDev1** [comment]
I'll update the encoder in the next version. This should fix the issue.
