### ISSUE TITLE
Feature request preserve smallest size

### ISSUE THREAD

**Issue by dill-shower** [JacobDev1/xl-converter#45]
### Feature Description

Preserve the original image if the encoding result is larger than the original image

### Technical Details

Sometimes file compression results in the result file being larger than the original file. It would be useful to add the ability to copy the original file to the results folder in such a situation instead of copying the larger result file

### Existing Implementations

XmView

**Comment by JacobDev1** [comment]
This feature will appear in version `1.0.2`. You will find it in the settings.

**Comment by dill-shower** [comment]
Thanks!
