### ISSUE TITLE
Add XL Converter to Scoop

### ISSUE THREAD

**Issue by o-l-a-v** [JacobDev1/xl-converter#48]
### Feature Description

Add XL Converter to Scoop bucket "Extras" (<https://github.com/ScoopInstaller/Extras>), for easier install and update of XL Converter.

I've already created a PR:

* <https://github.com/ScoopInstaller/Extras/pull/13719>

When/if approved: Add info about installing with Scoop to README or <https://codepoems.eu/xl-converter/>?

### Technical Details

* Install with: `scoop install extras/xl-converter`
* Update with: `scoop update --all`

### Existing Implementations

Not relevant.

**Comment by JacobDev1** [comment]
Hi,

This seems convenient. I appreciate your effort.

The installer has a task called `install_vcredist` which installs `vc_redist 14`. Could you check if this routine is run correctly by Scoop?

[Installer source](https://github.com/JacobDev1/xl-converter/blob/stable/misc/install.iss)

**Comment by o-l-a-v** [comment]
Hmm, I'll see if it can be added as a dependency in the Scoop manifest.

---

Edit: Scoop uses "innoextract", which seems to handle that just fine?

<img width="682" alt="image" src="https://github.com/user-attachments/assets/8af157f8-b53e-4364-9882-406e2eb242a7">

* About manifest authoring: <https://github.com/ScoopInstaller/Scoop/wiki/App-Manifests>
* innoextract: <https://constexpr.org/innoextract/>

**Comment by JacobDev1** [comment]
Ah, I see. This is problematic.

While the application itself includes `vc_redist`, the `magick.exe` dependency in `xl-converter/bin/win/` does not. That's how the official ImageMagick build is packaged.

**Microsoft Visual C++ Redistributable 2015 - 2022**  dependency can be downloaded from here:

```txt
https://aka.ms/vs/17/release/vc_redist.x64.exe
```

Unfortunately, it's not a static link. The checksum will change. Perhaps, there is a Scoop package for it already?

**Comment by o-l-a-v** [comment]
Aha. 🤔 There seems to be a package for VCRedist v14 / 2015++:

* <https://github.com/ScoopInstaller/Extras/blob/master/bucket/vcredist2022.json>

I'll try to add it as a dependency and see what happens.

**Comment by o-l-a-v** [comment]
It worked, but it installs both x86 and x64 VCRedist:

<img width="832" alt="image" src="https://github.com/user-attachments/assets/53f0943d-c06e-48db-9ad6-61dadd273475">

That's the cost of convenience I guess.

I'll add it to the PR.

**Comment by JacobDev1** [comment]
Yes, that's the one.

Without `vc_redist` the DLL errors will appear when you try to use ImageMagick (e.g. converting to WebP).

Backend rework is planned some time in the future, so this inconsistency shouldn't always be the case.

**Comment by JacobDev1** [comment]
Great, everything seems working.

I added the Scoop package to the download page.
