### ISSUE TITLE
Stuck right at the end

### ISSUE THREAD

**Issue by sm18lr88** [JacobDev1/xl-converter#5]
First: thanks for the app; it's great!

I'm using [xl-converter-win-0.9.4-x86_64.exe](https://github.com/JacobDev1/xl-converter/releases/download/v0.9.4/xl-converter-win-0.9.4-x86_64.exe) in Windows 11.

Second time in a large batch conversion it gets stuck right at the end like this:

![image](https://github.com/JacobDev1/xl-converter/assets/64564447/a096a065-6337-4947-92b7-b1c3d5ada889)

I literally plan to gift this app to my mom for Christmas. She's older and has a massive collection of family photos in very suboptimal formats.

**Comment by JacobDev1** [comment]
Hi, I'm glad you liked the app.

I'll look into this problem.

~The Developer

**Comment by JacobDev1** [comment]
After running many stress tests I have discovered some problems.

To fix them, I have added a safety check to `Smallest Lossless` and a mutex locker to the file renaming code. b378e01 7a77857

This should mostly eliminate the problem. More work on stability is to be done in the future.

~The Developer
