### ISSUE TITLE
Feature request: Add support for e11 (effort 11) option

### ISSUE THREAD

**Issue by dill-shower** [JacobDev1/xl-converter#50]
### Feature Description

The latest version of Cjxl now includes support for effort 11, which provides even more aggressive image compression. Currently, xl-converter doesn't allow users to select an effort level higher than 10. Although it may be time-consuming, some users might prefer having this option available.

Could you please consider implementing the ability to specify e11 in xl-converter? This would align the program with the latest Cjxl capabilities and give users more control over their compression settings

### Technical Details

Effort 11?

### Existing Implementations

This message on cjxl repo https://github.com/libjxl/libjxl/issues/3720#issuecomment-2266330255

**Comment by JacobDev1** [comment]
I had already thought of that, but upon closer inspection, it didn't seem practical.

I performed a small benchmark:

|Args|Elapsed|File Size in bytes|
|-|-|-|
|`-e 11 -q 100 --allow_expert_options`|1 h 22 m 59 s|126,103|
|`-e 10 -q 100`|18 s|144,996|
|`-e 9 -q 100`|5 s|159,864|

###### Image data: desktop screenshot 1920x1080; Environment: i5 4590; Linux Mint 21.2; `cjxl` from `libjxl v0.10.3`

Regarding lossy, Effort 11 resulted in the same processing time as Effort 10 and a matching checksum. This leads me to believe it is only available for lossless.

XL Converter has many safeguards preventing users from hurting themselves. This is not something that belongs in a user-friendly program.

I'll revisit it in the future if new versions change its implementation.
