### ISSUE TITLE
Error when converting from readable and editable TIFF file

### ISSUE THREAD

**Issue by RafaelLinux** [JacobDev1/xl-converter#56]
### Version

1.0.2

### OS

Linux

### Description

xl-convert fails while trying to convert from some kind of TIFF files, giving distinct errors on depending output format.
![image](https://github.com/user-attachments/assets/c3f09efa-0952-4759-a1a4-c04226ff7546)
[xl_converter_exceptions.csv](https://github.com/user-attachments/files/16662361/xl_converter_exceptions.csv)

https://www.transfernow.net/dl/20240819J0OZW0sW

### Steps to Reproduce

1. Load attached TIFF file in xl-convert
2. Try to convert to WebP or JXL 

### Expected Result

To convert file

### Current Result

There are distinct message error in each output case.

### Input Formats

TIFF

### Output Format

JPEG XL

### Additional Information (Optional)

Other TIFF files are converted w/o issues

**Comment by JacobDev1** [comment]
GIMP suggests the image may be corrupted.

![screenshot](https://github.com/user-attachments/assets/f4ff696c-6a2f-4812-9de0-6d80395dd53c)

ImageMagick output:

```
magick: Unknown field with tag 11 (0xb) encountered. `TIFFReadDirectory' @ warning/tiff.c/TIFFWarnings/958.
magick: Unknown field with tag 18246 (0x4746) encountered. `TIFFReadDirectory' @ warning/tiff.c/TIFFWarnings/958.
magick: Unknown field with tag 18249 (0x4749) encountered. `TIFFReadDirectory' @ warning/tiff.c/TIFFWarnings/958.
magick: Unknown field with tag 40965 (0xa005) encountered. `TIFFReadCustomDirectory' @ warning/tiff.c/TIFFWarnings/958.
magick: Incompatible type for "FileSource"; tag ignored. `TIFFFetchNormalTag' @ warning/tiff.c/TIFFWarnings/958.
magick: Incompatible type for "SceneType"; tag ignored. `TIFFFetchNormalTag' @ warning/tiff.c/TIFFWarnings/958.
magick: Unknown field with tag 18246 (0x4746) encountered. `TIFFReadDirectory' @ warning/tiff.c/TIFFWarnings/958.
magick: Unknown field with tag 18249 (0x4749) encountered. `TIFFReadDirectory' @ warning/tiff.c/TIFFWarnings/958.
magick: TIFF directory is missing required "ImageLength" field. `MissingRequired' @ error/tiff.c/TIFFErrors/599.
```

Issues with TIFFs are common. It's extremely difficult to cover all edge cases for TIFF decoding. You will occasionally encounter incompatible TIFFs.

If you want to investigate similar errors by yourself, go to Settings -> Advanced and click on "Start Logging".

The logs are located in `~/.config/xl-converter/logs`.

**Comment by RafaelLinux** [comment]
I'm a user of Krita, GIMP, DarkTable and Digikam and I must say that GIMP is not the best reference in terms of format handling, but even so, GIMP on Linux reads that file without problems. It only warns me that it has two pages and then loads it without problems.  This is the window that GIMP shows me (is not an error, is warning me there are two pages in that TIFF):
![imagen](https://github.com/user-attachments/assets/ce6cc873-dba1-4d6d-8b1b-5f9258031807)

TIFF has an added difficulty (as I'm sure you know, there are jokes about what the acronym TIFF means precisely because of the non-standard sub-types). That is, both Gwenview and the other applications I've mentioned read that file perfectly well. Krita even edits it without asking, because that extra layer contains no data. 

MediaInfo read it correctly too:
```
DSC00445_0001.tif
Format                                   : TIFF
File size                                : 47.4 MiB
Writing application                      : SONY  darktable 1.0.5
Writing library                          : DSLR-A700

Image
Format settings                          : Big
Width                                    : 2 570 pixels
Height                                   : 3 368 pixels
Color space                              : RGB
Bit depth                                : 16 bits
Encoded date                             : 2012:09:23 02:00:00
Density                                  : 300 dpi
ColorSpace_ICC                           : RGB
```

That said, it is very likely that you get this error - I imagine on Windows - because of the libraries you are using in GIMP. **The file is NOT corrupt**,.

Additional note: The TIFF files I use are generated from both DarkTable and DigiKam.

**Comment by JacobDev1** [comment]
The image can be either corrupted, poorly encoded, or just incompatible.

The fact is, the official AppImage build of ImageMagick can't read it. Every program I tested displays errors when converting this image. I used GIMP because it's what a typical user edits images with.

Image viewers are a poor metric for measuring corruption. They will typically open a slightly corrupt image without complaining.

XL Converter is not focused on an extensive TIFF support. You should use something else. In your case, using Darktable may be the best choice. For the best experience, transcode TIFFs generated with Darktable using Darktable.

All I can tell you is ImageMagick cannot read it. There is no use in complaining about TIFF to me. The current backend doesn't allow me to do anything about this. This format is extremely complex with many edge cases. You need specialized software.

**Comment by RafaelLinux** [comment]
Krita, GIMP (on Linux), Darktable, Digikam, Gwenview, XnConvert, XnViewMP, ShowFoto ... none of these programs give problems reading and exporting that TIFF file. However, you tell me that every program you tested give you an error. Which operating system are you using, because earlier I deduced that it was Windows because GIMP doesn't give me any errors, but you didn't confirm it.

As for me, I have confirmed as you say that it is ImageMagick that throws the error ‘magick: TIFF directory is missing required “ImageLength” field.’ but this does not imply that ImageMagick does not have an error or that it considers something wrong with the file that it cannot interpret. All programs using ImageMagick will fail with images of the same type until they correct that interpretation problem. 

Moreover, a free conversion program very similar to yours that also uses ImageMagick underneath, simply does not read the image, which speaks very positively of your application's error handling, which at least informs the user of a problem.

**Comment by JacobDev1** [comment]
OS: Linux Mint 21.2 based on Ubuntu 22.04.

|Program|Success|Notes|
|-|-|-|
|GIMP|Partial|Loads the first page and suggests the image may be corrupted.|
|GIMP (Flatpak)|Partial|Same as above.|
|XnConvert|Partial|Processes image with a warning in the console.|
|XnConvert (Flatpak)|Partial|Same as above.|
|ImageMagick (AppImage)|Fail|Fails to read image with errors.|
|Krita (AppImage)|Partial|Loads the first page and displays errors in stderr.|

Note: Flatpaks behave consistently across all distros.

I also tested on Windows 10 and the behavior was similar.

In general, most GUI software will ignore errors. If you don't see them, this does not mean the image was read correctly in full.

Regarding Krita, it silently ignores errors. To see them, you have to run the program from the terminal like this:

```bash
./krita-5.2.3-x86_64.appimage
```

Errors after loading the image.

```
krita.file: "TIFFReadDirectory: Unknown field with tag 11 (0xb) encountered"
krita.file: "TIFFReadDirectory: Unknown field with tag 18246 (0x4746) encountered"
krita.file: "TIFFReadDirectory: Unknown field with tag 18249 (0x4749) encountered"
krita.file: "TIFFFetchNormalTag: Incorrect value for \"RichTIFFIPTC\"; tag ignored"
krita.general: Invalid metadata name: "import_timestamp"
krita.general: Invalid metadata name: "change_timestamp"
krita.general: Invalid metadata name: "export_timestamp"
krita.general: Invalid metadata name: "print_timestamp"
krita.general: Invalid metadata name: "xmp_version"
krita.general: Invalid metadata name: "raw_params"
krita.general: Invalid metadata name: "auto_presets_applied"
krita.general: Invalid metadata name: "history_end"
krita.general: Invalid metadata name: "iop_order_version"
krita.general: Invalid metadata name: "history_current_hash"
krita.general: Invalid metadata name: "masks_history"
krita.file: "MissingRequired: TIFF directory is missing required \"ImageLength\" field"
```

The file itself is missing `ImageLength` which means it does not conform to the TIFF specs.

TIFF specification revision 6.0 Final; section "Required Fields for RGB Images" reads:

|TagName|Decimal|Hex|Type|Value|
|-|-|-|-|-|
|ImageLength|257|101|SHORT or LONG||

[Full specs](https://web.archive.org/web/20210108174645/https://www.adobe.io/content/dam/udp/en/open/standards/tiff/TIFF6.pdf)

XL Converter works best with PNG. I was reluctant to add TIFF support in #23 because of issues like this one.

Please use different software to process TIFFs. Darktable supports JPEG XL and AVIF. XnConvert is also an option (run Windows version through Wine for JPEG XL support).

**Comment by RafaelLinux** [comment]
As TIFF subformats are so numerous, it is normal that they show some warning or similar in the console, but the truth is that you will have checked that all the programs you have used (except in your case GIMP) loaded the image without corrupting it, that is, those messages refer to inconsistencies with what they expect in certain fields of the TIFF format and that (as they are TIFF subformats) they do not expect or do not know how to interpret. 

You suggest that I use DarkTable to export, but that image in question (look at the MediaInfo data I shared) is precisely from Darktable. 

I think that since all programs load and display that image without problems (as you may have checked), I'm sure that your program could also load and process it ignoring that particular error of the length, because it is clearly an interpretation problem when using some subtype of TIFF, because the truth is that the content of the image is valid and everything is correct despite the problem of the length of the field.

**Comment by JacobDev1** [comment]
All software detects errors in this picture. ImageMagick stops when an image cannot be correctly read in full. All encoders in XL Converter do. I could not find a way of making ImageMagick process this particular image.

The `magick` binary is included in the `xl-converter/bin` directory. By all means, try to figure out how to make it convert this TIFF to PNG. If you manage that, I may include it.

**Comment by JacobDev1** [comment]
As a sidenote, this is what happens when you open this TIFF in ImageGlass.

![cropped](https://github.com/user-attachments/assets/f20ad9eb-ee13-4b4b-8232-bcea3f1b8f42)

This program is also based on ImageMagick and I hold it in high regard.

**Comment by RafaelLinux** [comment]
I understand that is mainly an ImageMagic limitation although it is not surprising that they do not cover all cases of TIFF sub-formats using non-native algorithms.

I gather that the other applications I mentioned (including Gwenview) must use libraries that belong to the KDE Framework, and that's why all the ones that are part of its ecosystem, read those TIFFs without problems.

**Comment by JacobDev1** [comment]
You can try fixing those non-compliant TIFFs.

1. Install `libtiff-tools` with your package manager.
2. Use `tiffcp`

```
tiffcp input.tif output.tif
```

I tested this on 2 non-compliant TIFFs and they both got fixed. There is no loss of quality.

ImageMagick has stricter validation policies than typical GUI software. This isn't usually a problem unless a file is badly misencoded.

I want to emphasize that most GUI software does not read non-compliant TIFFs "without problems". The errors still occur, even if they're ignored. This may cause issues. Not all GUI software features detailed error reporting, so it may be impossible to tell. ImageMagick uses the same TIFF library as Gwenview (`libtiff`).

If you've already installed `libtiff-tools`, you can use `tiffinfo` to check for errors.

```bash
tiffinfo input.tif ; echo $?
```

Pay attention to the last line. If it's `1`, the image has serious problems. If it's `0`, the image is fine.

Compatibility can indeed be another problem, but this is a rabbit hole I don't want to get into.

**Comment by RafaelLinux** [comment]
I will try later today, cause in my distro there is no a `libtiff-tools` package, but seems `tiffcp` is in `tiff` package (Tools for Converting from and to the Tagged Image File Format)
