### ISSUE TITLE
Add file filters in the Add Image / Add Folder dialogs

### ISSUE THREAD

**Issue by redmoon1945** [JacobDev1/xl-converter#58]
### Feature Description

When adding files (or folders), it would be useful to specify that only certain types of files should be taken into account. For example, I have a directory of JPG, PNG and TIF files. It is too long to manually select only the JPG files, as they are numerous.  The filter would allow me to select one or many file extensions, here ".jpg". The app should show only the file fitting the filter.

### Technical Details

Modify the dialogs, set filters in Settings maybe  for default or override in the dialogs themselves.

### Existing Implementations

This is a common behavior.

**Comment by JacobDev1** [comment]
The program can sort image by extension. You can remove the ones you don't need.

1. Add your images.
2. Click on the first item you want removed.
3. Scroll up (or down), hold shift, and click on the last item you want removed.
4. Press the "Delete" key.

![Peek 2024-08-22 17-12](https://github.com/user-attachments/assets/415bfdad-be43-4019-aa61-93a3b6f3228d)

**Comment by JacobDev1** [comment]
Ah, fine. I can see why this could be useful. I'll test this once I finish some of the more important stuff.

**Comment by redmoon1945** [comment]
Great, thx :-)

**Comment by JacobDev1** [comment]
I added filters to the "Add Files" dialog, which will appear in `v1.0.3`.

I decided not to add filters to "Add Folder" because this is not a common feature, and the amount of dev time necessary is not justifiable.

You can use a file explorer to search for specific file types recursively, then drag and drop them onto the program.
