### ISSUE TITLE
Exception "Conversion could not finished" when output file is larger.

### ISSUE THREAD

**Issue by wx00** [JacobDev1/xl-converter#60]
### Version

1.0.2

### OS

Windows

### Description

I have encounter the exception when an output image is larger than its input.
I use jpeg as output format, jpeg encoder is jpegli, both "Do Not Delete Original When Result is Larger" and "Copy Original When Result is Larger" options are checked.
"Additional Encoder Arguments" is unchecked though that should not make any difference.

### Steps to Reproduce

choose a png file that will be smaller in png than in jpeg as input, click convert.

### Expected Result

No exception/error occurs, or an info/warn message hinting the output file is larger. Output file should have the same basename as input file.

### Current Result

Pops an exceptions window, `ID` shows F1, `Exception` says `Conversion could not finish. [WinError 2] The system cannot find the file specified:` + file path with input basename. 
Output file is actually in correct place, but with suffixes, e.g. `orig-001.png` -> `orig-001-58f.jpg`.

### Input Formats

png

### Output Format

jpeg

**Comment by JacobDev1** [comment]
Can you reliably reproduce this issue, or is it a random occurrence? Is the output folder set to a local or a network drive?

I was not able to reproduce it as of now.

The images with suffixes are temp files.

**Comment by wx00** [comment]
Yes, it can be reliably reproduce, I am trying on a different computer, can confirm this situation still exists. The output is on a local drive, Save To either Source Folder or Custon subfolder produces same result (with different tmp file name of course).

**Comment by JacobDev1** [comment]
Click "Save to File" on the exception pop up, save that file, and send it to my email at: contact@codepoems.eu

It contains data about settings.

**Comment by JacobDev1** [comment]
Now that I look at it, this may not actually be necessary. It's very light on data, and I need to include more of it.

Anyway, I'll introduce more stringent error handling to the code affected in the next update. I'll also test more and let you know if I'll be able to reproduce it.

**Comment by wx00** [comment]
Hi, I found another case when there is already a file have the target name `A.jpg`, the program will replace `A.jpg` with `A (1).png`, so the case may be it "Copy Original When Result is Larger" only when there is already a result file to be remove.

**Comment by wx00** [comment]
I think this is the branch that cause the problem, it did not rename the middle file `self.output`.
https://github.com/JacobDev1/xl-converter/blob/fa2a415bb110c252450fc41d877492876dac907d/core/worker.py#L439

I have a different file extention so it did not hit last branch at line 435
https://github.com/JacobDev1/xl-converter/blob/fa2a415bb110c252450fc41d877492876dac907d/core/worker.py#L435

and later `os.path.getsize(self.final_output)` in line 449 will raise an `OSError` because self.final_output does not exist.
https://github.com/JacobDev1/xl-converter/blob/fa2a415bb110c252450fc41d877492876dac907d/core/worker.py#L449

**Comment by JacobDev1** [comment]
Issues like this are difficult to troubleshoot. You should provide:
- Folder structure (`tree`) for both input and output
- Output settings
- The state of relevant settings (including "Duplicates")
- The steps to reproduce
- Expected and current results 

It's hard to work with insufficient and ambiguous descriptions.

If you set "Duplicates" to "Replace", files may get replaced.

I checked again and could not find issues with the system. However, there are a lot of edge cases to cover so I do expect bugs. Reproducing them requires detailed descriptions.

**Comment by JacobDev1** [comment]
I've successfully reproduced the issue. It occurs under the following conditions:
- "Duplicates" set to "Replace"
- "Copy Original When Result is Larger" enabled
- No filename conflict occurs

For now, you can avoid this bug by setting "Duplicates" to "Rename" if "Copy Original When Result is Larger" is enabled. I'll fix it in the next update.

**Comment by wx00** [comment]
Oh, how can I forget to include the "Duplicates" part when I reported the issue 😂
Thanks for the workaround solution.
