### ISSUE TITLE
A few small and insignificant bugs that you can safely ignore.

### ISSUE THREAD

**Issue by Ukhryuk-Hai** [JacobDev1/xl-converter#61]
1. After the conversion starts, user can still drag files onto the program window, they are added to the list, but will not be processed. Of course, it is better if this is blocked - to avoid ambiguous situations.

2. If user move the program window, the window with the conversion progress will remain in the same position. It is desirable that it maintains its position relative to the program coordinates. For example, this is implemented in **WinRAR** or **Duplicate File Detective** (by the way, this is the best program in this class).

3. Usually, when dragging files onto the window of some other program, it analyzes the file type and, if the type is inappropriate, the cursor takes the form "not available". Your program does not change the cursor.

**Comment by JacobDev1** [comment]
1. I will add a check to prevent this.

2. This will be added as well. 

3. I wrote this feature but I decided to scrap it for the following reasons:
- This is a gimmick and there is more important stuff to work on.
- None of the programs I have checked worked this way (GIMP, XnConvert, Affinity Designer, VLC, HandBrake, TreeSize, PureRef, Foobar2000, Reaper.fm, ImageGlass).
- It may have an impact on UI performance if dir content is to be scanned.
- Filtering is already done after drag and drop. This is unnecessary.

Supported file types (with extensions) are available in [the docs](https://xl-docs.codepoems.eu/supported-formats).
