### ISSUE TITLE
Remember last folder (Windows)

### ISSUE THREAD

**Issue by chromaniac2** [JacobDev1/xl-converter#66]
### Feature Description

Windows 10 user here. When I press the Add files button, it always load up `C:\Program Files (x86)\XL Converter` folder. If possible consider adding option to remember last folder and use that. 

### Technical Details

Remember the last used folder and use that instead of app folder. 

### Existing Implementations

It opens the file manager in app install directory.

**Comment by JacobDev1** [comment]
I modified file dialog handling, so now they will remember the last directory. I also changed the default location.
