### ISSUE TITLE
New downscaling method.

### ISSUE THREAD

**Issue by AniXL** [JacobDev1/xl-converter#67]
### Feature Description

The existing methods are pretty useful for most people but one more method that I personally believe is more useful than Percentage is the Megapixel method which I think is also more professional. That will be a nice addition to this great software.

### Technical Details

OK, I'm not very technically good at this so the best I can describe is that it scales the image by its entire pixel count.

### Existing Implementations

XnConvert

**Comment by JacobDev1** [comment]
I've added it. This feature will be available in the next version.
