### ISSUE TITLE
Consideration of adding a option to encode with avif svt-av1-psy 

### ISSUE THREAD

**Issue by NeinOclock** [JacobDev1/xl-converter#70]
### Feature Description

A option to select between aomenc or svt-av1-psy as a encoder for avif 

### Technical Details

Tune 4 was added recently to svt-av1-psy which seems to improve quality for images, there is a data set done by g82 wich show a improvement over libavif aom and jxl in the low to mediun quality while using a faster preset (svt psy s4, aomenc s4, jxl -e10)
https://svt-av1-psy.com/avif/
![dataset](https://github.com/user-attachments/assets/dd14849e-94f3-4eba-ad6c-ee3feb3c958f)

### Existing Implementations

https://github.com/gianni-rosato/libavif

**Comment by gianni-rosato** [comment]
Hi, I'm the lead maintainer of SVT-AV1-PSY & I maintain the libavif fork developed with special considerations for our encoder. If you are interested in implementing our encoder & you have any questions about implementation, let me know!

**Comment by JacobDev1** [comment]
I'll look into it.

@gianni-rosato Great, I may have some questions when I start integrating your encoder. If that's okay, I'll email you at the address you listed on your GitHub profile. My email is: contact@codepoems.eu thanks

**Comment by gianni-rosato** [comment]
Sure thing, sounds good! Feel free to reach out via any of my socials linked on my profile page on GitHub - I usually default to Matrix but email works fine for me.

**Comment by JacobDev1** [comment]
I added the SVT-AV1-PSY encoder. It will be available in the settings.

**Comment by gianni-rosato** [comment]
Awesome!

**Comment by Shanti099** [comment]
Hello Jacob,

Thank you for adding SVT-AV1-PSY
i'm trying to use custom settings, for example: "--crf 34 --preset 5" in "Additional encoder arguments" in section "avifenc AVIF",
but it seems, it's not working. Is it possible to use custom settings or I'm doing something wrong.
