### ISSUE TITLE
Unable to convert the image format

### ISSUE THREAD

**Issue by duzine** [JacobDev1/xl-converter#73]
### Version

1.0.2

### OS

Windows

### Description

Unable to convert the image format

### Steps to Reproduce

try it

[123.zip](https://github.com/user-attachments/files/17812996/123.zip)

### Expected Result

 an error has occurred.

### Current Result

Unable to convert the image format
 an error has occurred.

### Input Formats

png

### Output Format

JXL loseless

### Additional Information (Optional)

THANK YOU!

**Comment by JacobDev1** [comment]
1. Go to **Settings -> Advanced**
2. Scroll to the bottom
3. Press "Start Logging"
4. Perform conversion in a way that makes the error occur.
5. Next to "Start Logging" click on "Open Logs Folder" and send me the `logs.txt` file.

I can't reproduce the error right away, but I do admit there is something strange going on. The images bloat in size instead of shrink despite already being lossless PNG.

**Comment by JacobDev1** [comment]
After investigating, I found that these images have the wrong extension. They are JPEG images, not PNG. XL Converter needs the correct extension in the file name to work. It does not use magic numbers as you might expect.

**Comment by JacobDev1** [comment]
You can check the type of an image with `identify <file_name>`. This utility can be installed with Scoop (`scoop install main/imagemagick`). Then simply rename the file extension to match its file type (e.g. `.png` ->`.jpg`).

If after renaming the files the conversion still throws an error, then send me the `logs.txt` and I'll take a look.

**Comment by duzine** [comment]
Thank you for quickly resolving my question. 
I wonder if XL Converter can be set to output the original image if the conversion fails?

Or can it classify them into some newly created folders as a marker for errors?

**Comment by JacobDev1** [comment]
This falls outside the scope of this program. XL Converter stops the entire conversion thread if an error is encountered.

However, you can get a similar behavior by doing the following:
1. Copy all images into a new directory.
2. Add those new images as input.
3. Enable "Delete Original".
4. Convert.

The "Delete Original" will not be executed on failed conversions, leaving you only with the problematic images left.

That being said, this is best done via scripting. Use `cjxl` from `libjxl` for JPEG XL encoding.
