### ISSUE TITLE
Update Scoop manifest to use portable .7z and remove dependency on VCRedist

### ISSUE THREAD

**Issue by o-l-a-v** [JacobDev1/xl-converter#76]
### Feature Description

Update the Scoop manifest of XL Converter to use the protable .7z + remove dependency on VCRedist.

A PR is open, waiting for it to be merged. 😊

* <https://github.com/ScoopInstaller/Extras/pull/14607>

### Technical Details

See description.

### Existing Implementations

See description.

**Comment by JacobDev1** [comment]
I was just about to open a pull request there. Good to see you back.

Do you think the way the 7z archive is structured will cause problems for the GitHub bot updating the manifests? The `extract_dir` would need to be updated on every release. Originally, I thought about including the InnoSetup file so the auto update can do its thing.

I would like to hear your opinion on this.

**Comment by JacobDev1** [comment]
I just noticed you also extended the `autoupdate` with `extract_dir`. This will work then. Thanks

**Comment by o-l-a-v** [comment]
Yep, we should be good. 🤞🏻
