### ISSUE TITLE
Metadata preservation with ExifTool doesn't seem to work.

### ISSUE THREAD

**Issue by mn7216** [JacobDev1/xl-converter#8]
The "ExifTool - Preserve" does not copy over any metadata to the resulting .jxl file. Tested with multiple .jpg and .png inputs

I have reinstalled exiftool and xl converter yet this persists. ExifTool is also in PATH and functions from there by itself

**Comment by JacobDev1** [comment]
Hello!

XL Converter uses its own copy of ExifTool binaries located in `xl-converter/bin`.

Are you using Linux or Windows? I assume when you run ExifTool manually (from command line), it does work fine? Please do also include the ExifTool commands you are using, as this may be helpful.

**Comment by JacobDev1** [comment]
Please try the new version I released yesterday. The new error handling should tell you what is wrong.

I was not able to reproduce the issue.

Tips for power users:
- Feel free to swap ExifTool binaries with the latest in `xl-converter/bin`
- When running from source, you can set logging `level` to `DEBUG` in `data/constants.py` to view all processes' output

Even If ExifTool is found to work correctly, you may still experience issues as JPEG XL is still relatively new.

**Comment by JacobDev1** [comment]
Unfortunately, I was not able to reproduce the reported bug.

I will close the issue for now, because the discussion became stale.

The comment section is still open, so feel free to contribute.
